template = "https://github.com/giellalt/template-lang-und"
rev_id = 259
template_sha = "dbafdbc00bdeb17f80ec54b2fd5d6ae330f25f51"

[replacements]
__GLOTTOLOG_ID__ = "roma1327"
__REPO__ = "lang-ron"
__UND2C__ = "ro"
__UNDEFINED__ = "Romanian"
__UND__ = "ron"
